Update i3-workspace-names-daemon's dependencies
Gachicam/gachicam-overlay pull request #33
Opened 2022-07-20 03:51 UTC by xecua

多分3.10でも動く(テストがないのでわからんけど手元では動いてそう)
あと依存が抜けてたので追加

2022-08-06 17:50 UTC, pois0 requested changes
Revision の付与と 著作権表示の年を更新するべき

2022-08-07 02:18 UTC, xecua commented
Revisionの付与とは

2022-08-07 07:50 UTC, pois0 requested changes

2022-08-07 07:50 UTC, pois0 commented on x11-misc/i3-workspace-names-daemon/i3-workspace-names-daemon-0.15.0-r1.ebuild
> +# Copyright 2022 Gentoo Authors
```suggestion
# Copyright 2021-2022 Gentoo Authors
```

2022-08-07 12:25 UTC, pois0 approved these changes

2022-08-07 15:59 UTC, merged